### ISSUE TITLE
Error in 'make -C src' of Building FastSynth

### ISSUE THREAD

**Issue by Charlie0257** [natasha-jeppu/Trace2Model#1]
when I step to 'maka -C src', there is a error ocurring :(

> root@charlie:/home/ustc/fastsynth/lib/cbmc# make -C src
> make: Entering directory '/home/ustc/fastsynth/lib/cbmc/src'
> 
> make  -C big-int
> make[1]: Entering directory '/home/ustc/fastsynth/lib/cbmc/src/big-int'
> make[1]: Nothing to be done for 'first_target'.
> make[1]: Leaving directory '/home/ustc/fastsynth/lib/cbmc/src/big-int'
> 
> make  -C util
> make[1]: Entering directory '/home/ustc/fastsynth/lib/cbmc/src/util'
> g++ -c -DSATCHECK_MINISAT2 -MMD -MP -std=c++11 -O2 -DHAVE_MINISAT2 -Wall -pedantic -Werror -Wno-deprecated-declarations -I .. -o allocate_objects.o allocate_objects.cpp
> In file included from allocate_objects.h:16:0,
>                  from allocate_objects.cpp:9:
> std_code.h: In function ‘bool detail::can_cast_code_impl(const exprt&, const Tag&)’:
> std_code.h:119:56: error: call of overloaded ‘expr_try_dynamic_cast(const exprt&)’ is ambiguous
>    if(const auto ptr = expr_try_dynamic_cast<codet>(expr))
>                                                         ^
> std_code.h:119:56: note: candidates are:
> In file included from std_code.h:17:0,
>                  from allocate_objects.h:16,
>                  from allocate_objects.cpp:9:
> expr_cast.h:91:6: note: typename detail::expr_try_dynamic_cast_return_typet<T, TExpr>::type expr_try_dynamic_cast(TExpr&) [with T = codet; TExpr = const exprt; typename detail::expr_try_dynamic_cast_return_typet<T, TExpr>::type = const codet*]
>  auto expr_try_dynamic_cast(TExpr &base)
>       ^
> expr_cast.h:117:14: note: optionalt<T> expr_try_dynamic_cast(TExpr&&) [with T = codet; TExpr = const exprt&; optionalt<T> = nonstd::optional_lite::optional<codet>]
>  optionalt<T> expr_try_dynamic_cast(TExpr &&base)
>               ^
> In file included from allocate_objects.h:16:0,
>                  from allocate_objects.cpp:9:
> std_code.h: In function ‘bool detail::can_cast_side_effect_expr_impl(const exprt&, const Tag&)’:
> std_code.h:1611:68: error: call of overloaded ‘expr_try_dynamic_cast(const exprt&)’ is ambiguous
>    if(const auto ptr = expr_try_dynamic_cast<side_effect_exprt>(expr))
>                                                                     ^
> std_code.h:1611:68: note: candidates are:
> In file included from std_code.h:17:0,
>                  from allocate_objects.h:16,
>                  from allocate_objects.cpp:9:
> expr_cast.h:91:6: note: typename detail::expr_try_dynamic_cast_return_typet<T, TExpr>::type expr_try_dynamic_cast(TExpr&) [with T = side_effect_exprt; TExpr = const exprt; typename detail::expr_try_dynamic_cast_return_typet<T, TExpr>::type = const side_effect_exprt*]
>  auto expr_try_dynamic_cast(TExpr &base)
>       ^
> expr_cast.h:117:14: note: optionalt<T> expr_try_dynamic_cast(TExpr&&) [with T = side_effect_exprt; TExpr = const exprt&; optionalt<T> = nonstd::optional_lite::optional<side_effect_exprt>]
>  optionalt<T> expr_try_dynamic_cast(TExpr &&base)
>               ^
> ../common:212: recipe for target 'allocate_objects.o' failed
> make[1]: *** [allocate_objects.o] Error 1
> make[1]: Leaving directory '/home/ustc/fastsynth/lib/cbmc/src/util'
> Makefile:75: recipe for target 'util.dir' failed
> make: *** [util.dir] Error 2
> make: Leaving directory '/home/ustc/fastsynth/lib/cbmc/src'
Hope to help me solve this issue

**Comment by natasha-jeppu** [comment]
Thank you for raising this issue. 
Which operating system are you using? 
This seems to be a CBMC installation issue. Kindly refer to the [CBMC](https://github.com/diffblue/cbmc/blob/develop/COMPILING.md) git repository to ensure all dependencies are correctly installed.
