### ISSUE TITLE
Missing files / outdated instructions

### ISSUE THREAD

**Issue by threewisemonkeys-as** [natasha-jeppu/Trace2Model#2]
Step 4 of the Setup Instructions mention that fastsynth can be tested using the files `aux_files/simplify_event.sl` and `aux_files/gen_event_update.sl`.

However, these files are not present in the current repository.

**Comment by natasha-jeppu** [comment]
Thank you for pointing this out. The repo has been updated. You may use `gen_event.sl` or `gen_event_update.sl` for testing fastsynth. These are temporary files that are generated while running the Trace2Model tool.

**Comment by threewisemonkeys-as** [comment]
Thanks!
